//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabelAppS2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.ContractService = new HashSet<ContractService>();
            this.Rent = new HashSet<Rent>();
            this.Request = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public int ClientId { get; set; }
        public System.DateTime StartDate { get; set; }
        public int ContractTypeId { get; set; }
        public string ReasonOfEnd { get; set; }
        public string Bill { get; set; }
        public Nullable<System.DateTime> DateOfEnd { get; set; }
        public int EquipmentId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ContractType ContractType { get; set; }
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractService> ContractService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
