//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabelAppS2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractService
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Service Service { get; set; }
    }
}
