//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabelAppS2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.EmployeeRequest = new HashSet<EmployeeRequest>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public System.DateTime StartDate { get; set; }
        public int ContractId { get; set; }
        public int ServiceId { get; set; }
        public int ServiceVariationId { get; set; }
        public int ServiceTypeId { get; set; }
        public int ServiceStatusId { get; set; }
        public string ServiceType { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<System.DateTime> DateOfEnd { get; set; }
        public int ProblemTypeId { get; set; }
    
        public virtual Contract Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeRequest> EmployeeRequest { get; set; }
        public virtual ProblemType ProblemType { get; set; }
        public virtual Service Service { get; set; }
        public virtual ServiceStatus ServiceStatus { get; set; }
        public virtual ServiceType ServiceType1 { get; set; }
        public virtual ServiceVariation ServiceVariation { get; set; }
    }
}
